In [18]:
# 기본셋팅
import pandas as pd
table = pd.read_csv('./team6_low.csv')

In [19]:
# 기본정보 파악
table.head()

,날짜,기록 시간,기록자,호선,탑승역,하차역,지나온 역 수,시간,붐빔 정도,노약자석 빈자리 여부,성별,비어있었던 역 수,연령대,뱃지 여부,임산부 여부,무거운 짐 여부,행동,기타 특이사항,짐 종류,Unnamed: 19
0,07/31,19:10,재민,5.0,공덕,여의도,3.0,6.0,N,NaN,여,NaN,중년,X,X,O,"이어폰, 핸드폰",NaN,"쇼핑백, 장우산",붐빔 여부 \n- F (Full) : 열차 칸에 서있는 사람이 20명 초과인 경우\...
1,07/31,19:21,재민,9.0,여의도,신논현,10.0,20.0,F,NaN,여,NaN,중년,X,X,X,핸드폰,임산부석 비워달라는 방송이 나왔으나 아랑곳하지 않음,NaN,NaN
2,07/31,19:28,재민,9.0,여의도,신논현,10.0,NaN,F,NaN,여,NaN,청년,X,X,X,핸드폰,NaN,NaN,NaN
3,07/31,19:32,재민,9.0,여의도,신논현,10.0,NaN,F,NaN,여,NaN,청년,X,O,X,핸드폰,NaN,NaN,NaN
4,07/31,22:38,재민,10.0,선정릉,야탑,12.0,24.0,F,NaN,여,NaN,청년,O,O,X,"핸드폰, 대화",NaN,NaN,NaN

In [23]:
# columns 확인
table.columns

Index(['날짜', '기록 시간', '기록자', '호선', '탑승역', '하차역', '지나온 역 수', '시간', '붐빔 정도',
       '노약자석 빈자리 여부', '성별', '비어있었던 역 수', '연령대', '뱃지 여부', '임산부 여부', '무거운 짐 여부',
       '행동', '기타 특이사항', '짐 종류', 'Unnamed: 19'],
      dtype='object')

In [25]:
# 필요없는 column 데이터 드롭
table.drop('Unnamed: 19', axis=1).head()

,날짜,기록 시간,기록자,호선,탑승역,하차역,지나온 역 수,시간,붐빔 정도,노약자석 빈자리 여부,성별,비어있었던 역 수,연령대,뱃지 여부,임산부 여부,무거운 짐 여부,행동,기타 특이사항,짐 종류
0,07/31,19:10,재민,5.0,공덕,여의도,3.0,6.0,N,NaN,여,NaN,중년,X,X,O,"이어폰, 핸드폰",NaN,"쇼핑백, 장우산"
1,07/31,19:21,재민,9.0,여의도,신논현,10.0,20.0,F,NaN,여,NaN,중년,X,X,X,핸드폰,임산부석 비워달라는 방송이 나왔으나 아랑곳하지 않음,NaN
2,07/31,19:28,재민,9.0,여의도,신논현,10.0,NaN,F,NaN,여,NaN,청년,X,X,X,핸드폰,NaN,NaN
3,07/31,19:32,재민,9.0,여의도,신논현,10.0,NaN,F,NaN,여,NaN,청년,X,O,X,핸드폰,NaN,NaN
4,07/31,22:38,재민,10.0,선정릉,야탑,12.0,24.0,F,NaN,여,NaN,청년,O,O,X,"핸드폰, 대화",NaN,NaN

In [27]:
# columms 정리

# date, time, line, start, stop
# crowdedness, E, N, F, old_age_seat
# is_empty, is_empty_count, female, male
# age, child, teenage, youth, middle_age, old_age
# badge, pregnant
# heavy
# behavior1, behavior2, behavior3, cellphone, talking, calling, reading, makeup, eating, writing

# 1. 뱃지여부, 임산부여부, 무거운 짐 여부 0(없음),1(있음) 처리
# 2. 노약자석 빈자리 여부 0(빈자리 있음 O), 1(빈자리 없음) 처리
# 3. 성별 여자, 남자 분리
# 4. 붐빔정도 분리
# 5. 연령대 분리